CSRF changes related to : backlog-30582 and backlog-30660
pentaho/pentaho-platform pull request #4992
Opened 2022-01-28 11:54 UTC by sVarma1992

CSRF changes related to : backlog-30582 and backlog-30660

2022-01-28 12:14 UTC, buildguy commented
### :white_check_mark: Build finished in 20m 16s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/pentaho-solutions,user-console
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

2022-01-28 16:56 UTC, dcleao requested changes
Please provide one PR per story, or, at a minimum, one commit per story.

Also, this PR is also including changes from BACKLOG-30581.

Additionally, please, like is the case of other request matchers in this file, leave an empty line between request matcher elements (between the request matcher element and the comment of the following one).

Thanks!

2022-01-31 06:31 UTC, buildguy commented
### :white_check_mark: Build finished in 20m 20s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/pentaho-solutions,user-console
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

2022-01-31 12:41 UTC, dcleao requested changes

2022-01-31 12:41 UTC, dcleao commented on assemblies/pentaho-solutions/src/main/resources/pentaho-solutions/system/applicationContext-spring-security-csrf.xml
> +          GET api/system/refresh/mondrianSingleSchemaCache
Please add `GET /api/system/refresh/mondrianSchemaCache`

2022-02-01 05:10 UTC, sVarma1992 commented
Will raise a new PR with the guidelines mentioned in the review

2022-02-01 05:38 UTC, buildguy commented
### :white_check_mark: Build finished in 18m 53s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/pentaho-solutions,user-console
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

2022-02-02 06:36 UTC, sVarma1992 commented
Created a new PR with addressing the review comments

2022-02-02 06:36 UTC, closed without merging