Fixed PDI - 18988
pentaho/pentaho-platform pull request #5074
Opened 2022-05-06 13:07 UTC by VootkoorSamhitha

Fixed PDI - 18988: Username and Password exposed in cleartext on Server logs when adding or importing Hadoop Cluster

2022-05-06 14:47 UTC, peterrinehart requested changes

2022-05-06 14:47 UTC, peterrinehart commented on tomcat-logs/pom.xml
> +        <maven.compiler.source>11</maven.compiler.source>
This is building on JDK11 now, and should use the parameter already defined here: https://github.com/pentaho/maven-parent-poms/blob/master/pom.xml#L210

You shouldn't override this setting in lower projects unless it's essential; we're currently still targeting JDK8 for compatibility with certain big data drivers.

2022-05-06 14:52 UTC, peterrinehart commented
We need to update the commit message to begin with [PDI-18988] and not Fixed - PDI-18988.  This ensures that our other tools will link this issue to the Jira ticket automatically.

2022-05-07 09:06 UTC, buildguy commented
### :white_check_mark: Build finished in 36m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

2022-05-09 08:57 UTC, buildguy commented
### :x: Build failed in 28m
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2022-05-11 22:48 UTC, merged