[BISERVER-12830] - As a user I would like PUC to remember the language switching after relogin
pentaho/pentaho-platform pull request #5107
Opened 2022-06-29 17:37 UTC by andreramos89

Adding property in repository to account for locale change

2022-06-29 18:07 UTC, buildguy commented
### :white_check_mark: Build finished in 29m 29s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,extensions,user-console
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

2022-06-30 09:57 UTC, smmribeiro requested changes

2022-06-30 10:15 UTC, buildguy commented
### :white_check_mark: Build finished in 27m 2s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,extensions,user-console
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

2022-06-30 11:04 UTC, buildguy commented
### :white_check_mark: Build finished in 26m 29s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core,extensions,user-console
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

2022-06-30 13:58 UTC, bcostahitachivantara approved these changes

2022-07-05 09:42 UTC, merged