[PPP-4660] - Use of Vulnerable Component: Components/jackson-databind:2.9.10.2
pentaho/pentaho-platform pull request #5182
Opened 2023-01-06 14:54 UTC by andreramos89

@smmribeiro 
@bcostahitachivantara 
@renato-s

2023-01-06 16:10 UTC, buildguy commented
### :x: Build failed in 1h 15m 3s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions,user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **1664**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform-11/job/PR-5182/1/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2023-01-09 15:47 UTC, buildguy commented
### :white_check_mark: Build finished in 45m 40s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions,user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **1664**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform-11/job/PR-5182/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-01-10 16:11 UTC, buildguy commented
### :white_check_mark: Build finished in 44m 48s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions,user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **1664**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform-11/job/PR-5182/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-01-17 12:26 UTC, buildguy commented
### :x: Build failed in 39s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2023-01-17 15:48 UTC, andreramos89 commented on extensions/src/main/java/org/pentaho/platform/web/http/api/resources/MantleResource.java
> +    return Response.ok(  new HostsWrapper( getListHosts() ), MediaType.APPLICATION_JSON ).build();
A new push has been done

2023-01-18 12:26 UTC, smmribeiro approved these changes
Looks good.

2023-01-24 16:49 UTC, NJtwentyone commented on extensions/src/main/java/org/pentaho/platform/web/http/api/resources/HostsWrapper.java
> +
this class needs unit tests

2023-01-24 16:57 UTC, NJtwentyone commented on assemblies/pentaho-war/pom.xml
> -    <snakeyaml.version>1.13</snakeyaml.version>
you can't delete this property without replace/updating it in other places. You are getting a build error now

https://wingman.orl.eng.hitachivantara.com/blue/organizations/jenkins/projects%2Fplatform-11/detail/PR-5182/5/pipeline


`${snakeyaml.version} `is used in:

- ./repository/pom.xml:190:      <version>${snakeyaml.version}</version>
- ./assemblies/pentaho-war/pom.xml:860:      <version>${snakeyaml.version}</version>
- ./extensions/pom.xml:1851:      <version>${snakeyaml.version}</version>

2023-01-24 17:00 UTC, NJtwentyone commented on user-console/src/main/java/org/pentaho/mantle/client/MantleApplication.java
> +import com.google.gwt.core.client.*;
Dont't use star imports `.*.` your penatho checktyle should have prevented this.

2023-01-24 17:11 UTC, NJtwentyone commented on extensions/src/main/java/org/pentaho/platform/web/http/api/resources/MantleResource.java
> +      getPropFile();
I'm confused about this line.
`getPropFile();`

Before the values of file deeplink_allowed_urls.properties were used inside this function. But with the proposed changes, this file isn't used.

And why call a function that the results are never used?

2023-01-24 17:37 UTC, NJtwentyone commented on user-console/src/main/java/org/pentaho/mantle/client/MantleApplication.java
> +
You'll need test for MantleApplication as well. You can use this as an reference https://github.com/pentaho/pentaho-platform/blob/master/extensions/src/test/java/org/pentaho/platform/web/http/api/resources/EmailResourceTest.java

You won't have to do the MicroPlatform logic in #setup 

- https://github.com/pentaho/pentaho-platform/blob/master/extensions/src/test/java/org/pentaho/platform/web/http/api/resources/EmailResourceTest.java#L50-L52

Also, you won;t have to do the KettleEnvironment logic either

- https://github.com/pentaho/pentaho-platform/blob/master/extensions/src/test/java/org/pentaho/platform/web/http/api/resources/EmailResourceTest.java#L59
- https://github.com/pentaho/pentaho-platform/blob/master/extensions/src/test/java/org/pentaho/platform/web/http/api/resources/EmailResourceTest.java#L92

2023-01-24 17:43 UTC, NJtwentyone requested changes
Main points

- build error
- pentaho coding standards issues

2023-01-27 16:04 UTC, buildguy commented
### :x: Build failed in 1m 21s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2023-05-05 15:48 UTC, smmribeiro commented
Closing this and all "January 2023" related PRs for this issue (check this [comment](https://hv-eng.atlassian.net/browse/PPP-4660?focusedCommentId=1546417) and this [comment](https://hv-eng.atlassian.net/browse/PPP-4660?focusedCommentId=1543281)).

Too much time has passed and the risk of a PR being incomplete (or simply wrong) is too high.
I won't delete the original branch so that anyone picking up the development can see what was done previously.

2023-05-05 15:48 UTC, closed without merging

2023-05-05 15:48 UTC, smmribeiro commented
Closing this and all "January 2023" related PRs for this issue (check this [comment](https://hv-eng.atlassian.net/browse/PPP-4660?focusedCommentId=1546417) and this [comment](https://hv-eng.atlassian.net/browse/PPP-4660?focusedCommentId=1543281)).

Too much time has passed and the risk of a PR being incomplete (or simply wrong) is too high.
I won't delete the original branch so that anyone picking up the development can see what was done previously.