[BACKLOG-36970] [BACKLOG-36971] - Page Zoom (AA) - Browse Files - Select Folder - Properties
pentaho/pentaho-platform pull request #5241
Opened 2023-02-23 11:38 UTC by soagarwal1

2023-02-23 11:38 UTC, soagarwal1 commented
@pentaho/wcag Please review

2023-02-23 11:39 UTC, buildguy commented
### :x: Build failed in 1m 35s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2023-02-23 14:38 UTC, dcleao requested changes

2023-02-23 14:58 UTC, soagarwal1 commented on user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/fileproperties/FilePropertiesDialog.java
> +    setWidth( "490px" );
This does not matter because the content is always more than the provided height and takes up space according to the content

2023-02-23 16:14 UTC, soagarwal1 commented on user-console/src/main/java/org/pentaho/mantle/client/commands/AbstractFilePropertiesCommand.java
> +            dialog.setResponsive( true );
addressed

2023-02-23 16:14 UTC, soagarwal1 commented on user-console/src/main/java/org/pentaho/mantle/client/commands/AbstractFilePropertiesCommand.java
> +            dialog.addStyleName( "properties-dialog" );
addressed

2023-02-23 16:16 UTC, dcleao commented on user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/fileproperties/FilePropertiesDialog.java
> +    setWidth( "490px" );
Don't take me wrong, but, if it "does not matter", then maybe the change is not needed?
Maybe the new responsive CSS is already overriding/ignoring any fixed heights set in this way?

2023-02-23 16:22 UTC, soagarwal1 commented on user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/fileproperties/FilePropertiesDialog.java
> +    setWidth( "490px" );
That is the problem, making the dialog responsive is enforcing the min height and a scroll bar comes up even when there is ample space for both the dialog screens.

2023-02-23 16:23 UTC, soagarwal1 commented on user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/fileproperties/FilePropertiesDialog.java
> +    setWidth( "490px" );
Although this is better in a way that when we change tabs, the size of the dialog does not increase and does not do out of center

2023-02-23 16:23 UTC, buildguy commented
### :white_check_mark: Build finished in 13m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5241/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-02-23 22:12 UTC, dcleao commented on user-console/src/main/java/org/pentaho/mantle/client/commands/AbstractFilePropertiesCommand.java
> +            dialog.setResponsive( true );
Maybe not clear, but by that comment, I was also including the corresponding style name.

2023-02-24 08:45 UTC, soagarwal1 commented on user-console/src/main/java/org/pentaho/mantle/client/commands/AbstractFilePropertiesCommand.java
> +            dialog.setResponsive( true );
addressed

2023-02-24 08:45 UTC, soagarwal1 commented on user-console/src/main/java/org/pentaho/mantle/client/solutionbrowser/fileproperties/FilePropertiesDialog.java
> +    setWidth( "490px" );
addressed

2023-02-24 08:56 UTC, buildguy commented
### :white_check_mark: Build finished in 14m 17s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5241/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-02-24 09:44 UTC, buildguy commented
### :white_check_mark: Build finished in 13m 55s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5241/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-02-24 12:50 UTC, dcleao approved these changes

2023-02-27 12:13 UTC, varuntangirala approved these changes

2023-02-27 12:35 UTC, merged