[BACKLOG-36843]-Accessibility-Browse Files Perspective-Files List
pentaho/pentaho-platform pull request #5250
Opened 2023-03-03 09:02 UTC by phalguni-a

@pentaho/wcag, please review

2023-03-03 09:16 UTC, buildguy commented
### :white_check_mark: Build finished in 14m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5250/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-03-03 17:45 UTC, dcleao requested changes

2023-03-03 17:45 UTC, dcleao commented on user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.templates.js
> +          "<select class='body' aria-labelledby='filesHeader' multiple size='0' id='MyID'></select>" +
Could you give a more meaningful identifier? Or, is it forgotten and not needed?

2023-03-06 13:29 UTC, buildguy commented
### :white_check_mark: Build finished in 13m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5250/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-03-06 14:07 UTC, dcleao approved these changes

2023-03-06 14:40 UTC, buildguy commented
### :white_check_mark: Build finished in 13m 20s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5250/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-03-06 15:57 UTC, ddiroma approved these changes

2023-03-06 15:57 UTC, merged