[BACKLOG-37159]Fix failover scenario for chained LDAP servers
pentaho/pentaho-platform pull request #5251
Opened 2023-03-03 14:58 UTC by varuntangirala

2023-03-03 15:43 UTC, lucboudreau requested changes

2023-03-03 15:43 UTC, lucboudreau commented on extensions/src/main/java/org/pentaho/platform/plugin/services/security/userrole/ChainedUserDetailsService.java
>          // ignore and continue;
While we're fixing this, may as well add a log.debug() statement to at least be able to debug when this happens.

2023-03-03 15:44 UTC, buildguy commented
### :white_check_mark: Build finished in 45m 49s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1690**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5251/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-03-08 19:24 UTC, lucboudreau approved these changes

2023-03-08 19:48 UTC, buildguy commented
### :white_check_mark: Build finished in 44m 58s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1690**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5251/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-03-09 14:03 UTC, ddiroma approved these changes

2023-03-09 14:03 UTC, merged