[BACKLOG-36973] - fix for user dropdown in header getting out of screen
pentaho/pentaho-platform pull request #5254
Opened 2023-03-10 10:21 UTC by soagarwal1

@pentaho/wcag Please review

2023-03-10 10:34 UTC, buildguy commented
### :white_check_mark: Build finished in 12m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5254/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-03-10 12:55 UTC, dcleao requested changes
While this solves part of the issue, it does not solve it completely.

Choosing the "Administration" perspective still causes the user dropdown to wrap into a new line (but in a not good way), on a 320px wide viewport.
<img width="517" alt="PUC_Header_Administration" src="https://user-images.githubusercontent.com/284983/224321236-f21fb8cb-609b-4a79-84c3-6bd5e8222392.png">


Also, in the "Opened" perspective, the PUC toolbar buttons which are displayed also are not laying out properly in these circumstances. The modified properties affect this.

<img width="566" alt="PUC_Header_Opened" src="https://user-images.githubusercontent.com/284983/224321106-80b8fa6b-a334-437f-968b-69887f49e5df.png">

In my opinion, the main issue is to make the PUC toolbar be responsive, and it would be best to solve it as a whole.

2023-03-10 13:16 UTC, soagarwal1 commented
@dcleao Agree with you that it does solve part of the problem, and we need to solve the entire toolbar as a whole, but it is not within the scope of this story. This is a second commit for Browse Perspective Story which after being responsive is creating issues with keyboard navigation where because of this dropdown, not being a part of the visible viewport, shifts the viewport when used with keyboard navigation, even though there is no scroll. These changes do resolve that issue and later further changes can be done to make it responsive according to changes suggested by PD team.

2023-03-10 16:58 UTC, dcleao approved these changes

2023-03-13 05:06 UTC, varuntangirala approved these changes

2023-03-13 05:13 UTC, merged