[BACKLOG-37239][BACKLOG-37233]-Focus and Keyboard issues on Browser Files
pentaho/pentaho-platform pull request #5266
Opened 2023-03-23 12:59 UTC by phalguni-a

2023-03-23 13:13 UTC, buildguy commented
### :white_check_mark: Build finished in 14m 11s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5266/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-03-23 15:39 UTC, phalguni-a commented
@pentaho/wcag , Please review

2023-03-23 16:13 UTC, dcleao requested changes
All good except formatting.

2023-03-23 16:13 UTC, dcleao commented on user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js
> +          $target.children(".element").attr("tabindex",0);
Formatting is off.

2023-03-24 04:54 UTC, hv-vamsi approved these changes

2023-03-24 04:57 UTC, buildguy commented
### :white_check_mark: Build finished in 13m 11s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5266/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-03-24 05:10 UTC, buildguy commented
### :white_check_mark: Build finished in 12m 38s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5266/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2023-03-24 12:03 UTC, merged