Merging wcag into master
pentaho/pentaho-platform pull request #5442
Opened 2023-11-08 07:37 UTC by AAravind27

2023-11-08 09:07 UTC, buildguy commented
### :x: Build failed in 1h 29m 15s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.platform.util.versionchecker.PentahoVersionCheckReflectHelperTest.performVersionCheckTest</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **2865**, Failures: **1**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5442/1/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2023-11-09 06:20 UTC, phalguni-a approved these changes

2023-11-09 07:05 UTC, phalguni-a requested changes
Build seems to be getting failed. This needs to be merged only after the build is fixed.

2023-11-09 14:16 UTC, hv-vamsi approved these changes

2023-11-09 14:20 UTC, AAravind27 commented
Test failure appears to be either of https://thanos.orl.eng.hitachivantara.com/job/10.1/job/suite-release/88/testReport/org.pentaho.platform.util.versionchecker/PentahoVersionCheckReflectHelperTest/Test__3____platform_base___performVersionCheckTest/
or
https://thanos.orl.eng.hitachivantara.com/job/10.1/job/suite-release/88/testReport/org.pentaho.platform.util.versionchecker/PentahoVersionCheckReflectHelperTest/Test__4____platform_user_console___performVersionCheckTest/

2023-11-09 14:22 UTC, phalguni-a approved these changes

2023-11-09 14:32 UTC, merged