[BACKLOG-40086] Testing feedback subtasks [BACKLOG-40485][BACKLOG-40486]
pentaho/pentaho-platform pull request #5578
Opened 2024-04-16 21:01 UTC by singletonc

[BACKLOG-40086] Schedule Output Perspective : Allow user to browse Scheduled contents from a VFS location folder
Follow up sub-task:
[BACKLOG-40485] Disable file action buttons for multi-select, and disable double-click to "open" for VFS Connections
- These blocks/code will be modified in BACKLOG-40475 wherein we investigate enabling "open" for VFS Connection files
[BACKLOG-40486] Investigate ctrl+click in VFS Connection Files (cannot ctrl+click to add >1 to selection, only remove)
- Add `id` to file elements in cases wher `objectId` is missing in response object, use `path` instead

2024-04-16 21:03 UTC, buildguy commented
### :x: Build failed in 2m 9s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
Error fetching remote repo 'origin'
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2024-04-17 18:33 UTC, rmansoor approved these changes

2024-04-19 15:40 UTC, dcleao requested changes

2024-04-19 15:40 UTC, dcleao commented on user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js
> +      let selectedFilePath = fileClicked ? fileClicked.attr("path") : false;
Please use instead:
```js
const selectedFilePath = fileClicked ? fileClicked.attr("path") : null;
if (selectedFilePath != null && ...) {
}
```

2024-04-19 15:40 UTC, dcleao commented on user-console/src/main/resources/org/pentaho/mantle/public/browser/js/browser.js
> +      }
Idem.

2024-04-23 20:22 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-04-23 20:22 UTC, buildguy commented
### :white_check_mark: Build finished in 9m 44s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **12**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5578/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-04-24 10:34 UTC, dcleao approved these changes

2024-04-29 14:34 UTC, merged