[BISERVER-14644] - Users with password having certain special characters, or strings of characters, are not allowed to login to PUC
pentaho/pentaho-platform pull request #5597
Opened 2024-05-10 12:44 UTC by renato-s

Added URL  encoding to handle special characters before b64 encoding

2024-05-10 12:48 UTC, buildguy commented
### :x: Build failed in 2m 47s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
extensions,user-console
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2024-05-13 15:07 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-05-13 18:26 UTC, smmribeiro requested changes

2024-05-13 18:26 UTC, smmribeiro commented on extensions/src/main/java/org/pentaho/platform/web/http/api/resources/UserRoleDaoResource.java
> +    try {
Please remove the try-catch as it is only rethrowing the original exception (check SonarQube's report).

2024-05-14 08:48 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-05-14 08:48 UTC, buildguy commented
### :white_check_mark: Build finished in 30m 36s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
extensions,user-console
```
---
:ok_hand: All tests passed!
 
Tests run: **1573**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5597/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-05-14 08:56 UTC, smmribeiro approved these changes
Looks good!

2024-05-14 08:58 UTC, merged