[BISERVER-15169] Adding debug logging to backup and restore process
pentaho/pentaho-platform pull request #5811
Opened 2024-12-15 23:12 UTC by rmansoor

2024-12-15 23:42 UTC, buildguy commented
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[![👍 Frogbot scanned this pull request and did not find any new security issues.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-12-15 23:42 UTC, buildguy commented
### :warning: Build finished in 30m 13s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
api,assemblies/pentaho-solutions,extensions
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 11 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMondrianSchemas</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMondrianSchemas_noCatalogs</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMetadata_noModels</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testPerformExportMondrianSchemas_XmlUnsafeDataSourceInfoSaved</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportUsersAndRoles</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMondrianSchemas_AdditionalParametersSaved</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportDatasources</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMetaStore</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMetadata</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importexport.ZipExportProcessorTest.testPerformExport_withManifest</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.debug(String)" because the return value of "org.pentaho.platform.plugin.services.importexport.ZipExportProcessor.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importexport.ZipExportProcessorTest.testPerformExport_withoutManifest</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.debug(String)" because the return value of "org.pentaho.platform.plugin.services.importexport.ZipExportProcessor.getRepositoryExportLogger()" is null
```

</p></details>

  
Tests run: **1678**, Failures: **11**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5811/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-12-17 22:48 UTC, buildguy commented
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[![👍 Frogbot scanned this pull request and did not find any new security issues.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-12-17 22:48 UTC, buildguy commented
### :warning: Build finished in 27m 4s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
api,assemblies/pentaho-solutions,extensions
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 11 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMondrianSchemas</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMondrianSchemas_noCatalogs</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMetadata_noModels</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testPerformExportMondrianSchemas_XmlUnsafeDataSourceInfoSaved</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportUsersAndRoles</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMondrianSchemas_AdditionalParametersSaved</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportDatasources</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMetaStore</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMetadata</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importexport.ZipExportProcessorTest.testPerformExport_withManifest</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.debug(String)" because the return value of "org.pentaho.platform.plugin.services.importexport.ZipExportProcessor.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importexport.ZipExportProcessorTest.testPerformExport_withoutManifest</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.debug(String)" because the return value of "org.pentaho.platform.plugin.services.importexport.ZipExportProcessor.getRepositoryExportLogger()" is null
```

</p></details>

  
Tests run: **1678**, Failures: **11**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5811/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-12-18 02:49 UTC, buildguy commented
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[![👍 Frogbot scanned this pull request and did not find any new security issues.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-12-18 02:49 UTC, buildguy commented
### :warning: Build finished in 25m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
api,assemblies/pentaho-solutions,extensions
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 12 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.services.importer.PlatformImporterTest.testNoMatchingMime</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMondrianSchemas</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMondrianSchemas_noCatalogs</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMetadata_noModels</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testPerformExportMondrianSchemas_XmlUnsafeDataSourceInfoSaved</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportUsersAndRoles</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMondrianSchemas_AdditionalParametersSaved</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportDatasources</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMetaStore</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMetadata</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importexport.ZipExportProcessorTest.testPerformExport_withManifest</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.debug(String)" because the return value of "org.pentaho.platform.plugin.services.importexport.ZipExportProcessor.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importexport.ZipExportProcessorTest.testPerformExport_withoutManifest</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.debug(String)" because the return value of "org.pentaho.platform.plugin.services.importexport.ZipExportProcessor.getRepositoryExportLogger()" is null
```

</p></details>

  
Tests run: **1678**, Failures: **12**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5811/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-12-18 17:40 UTC, peterrinehart requested changes

2024-12-18 17:40 UTC, peterrinehart commented on extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/FileService.java
> +import java.util.*;
This needs to be expanded

2024-12-18 18:18 UTC, angel-ramoscardona approved these changes

2024-12-19 01:12 UTC, buildguy commented
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[![👍 Frogbot scanned this pull request and did not find any new security issues.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-12-19 01:12 UTC, buildguy commented
### :warning: Build finished in 28m 28s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
api,assemblies/pentaho-solutions,extensions
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 12 test(s) failed:

<details><summary><b>org.pentaho.platform.plugin.services.importer.PlatformImporterTest.testNoMatchingMime</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMondrianSchemas</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMondrianSchemas_noCatalogs</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMetadata_noModels</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testPerformExportMondrianSchemas_XmlUnsafeDataSourceInfoSaved</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportUsersAndRoles</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMondrianSchemas_AdditionalParametersSaved</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportDatasources</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMetaStore</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporterTest.testExportMetadata</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.info(String)" because the return value of "org.pentaho.platform.plugin.services.exporter.PentahoPlatformExporter.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importexport.ZipExportProcessorTest.testPerformExport_withManifest</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.debug(String)" because the return value of "org.pentaho.platform.plugin.services.importexport.ZipExportProcessor.getRepositoryExportLogger()" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.plugin.services.importexport.ZipExportProcessorTest.testPerformExport_withoutManifest</b> (click to expand)</summary><p>

```
Cannot invoke "org.pentaho.platform.api.util.IRepositoryExportLogger.debug(String)" because the return value of "org.pentaho.platform.plugin.services.importexport.ZipExportProcessor.getRepositoryExportLogger()" is null
```

</p></details>

  
Tests run: **1678**, Failures: **12**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5811/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-12-19 02:18 UTC, buildguy commented
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[![👍 Frogbot scanned this pull request and did not find any new security issues.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-12-19 02:18 UTC, buildguy commented
### :white_check_mark: Build finished in 26m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
api,assemblies/pentaho-solutions,extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1678**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5811/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-12-19 19:15 UTC, buildguy commented
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[![👍 Frogbot scanned this pull request and did not find any new security issues.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-12-19 19:15 UTC, buildguy commented
### :white_check_mark: Build finished in 27m 33s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
api,assemblies/pentaho-solutions,extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1678**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5811/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-12-19 20:48 UTC, angel-ramoscardona approved these changes

2024-12-19 21:27 UTC, buildguy commented
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[![👍 Frogbot scanned this pull request and did not find any new security issues.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-12-19 21:27 UTC, buildguy commented
### :white_check_mark: Build finished in 27m 40s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
api,assemblies/pentaho-solutions,extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1678**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5811/7/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-12-21 02:35 UTC, buildguy commented
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[![👍 Frogbot scanned this pull request and did not find any new security issues.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-12-21 02:35 UTC, buildguy commented
### :white_check_mark: Build finished in 26m 37s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
api,assemblies/pentaho-solutions,extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1678**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5811/8/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-12-21 03:00 UTC, buildguy commented
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[![👍 Frogbot scanned this pull request and did not find any new security issues.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-12-21 03:00 UTC, buildguy commented
### :white_check_mark: Build finished in 25m 34s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
api,assemblies/pentaho-solutions,extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1678**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5811/9/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-12-21 17:28 UTC, rmansoor commented on extensions/src/main/java/org/pentaho/platform/web/http/api/resources/services/FileService.java
> +import java.util.*;
It has been resolved

2024-12-22 03:52 UTC, buildguy commented
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[![👍 Frogbot scanned this pull request and did not find any new security issues.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-12-22 03:52 UTC, buildguy commented
### :white_check_mark: Build finished in 31m 18s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
api,assemblies/pentaho-solutions,extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1678**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5811/10/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-12-22 16:11 UTC, buildguy commented
### :x: Build failed in 3m 8s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl extensions
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2024-12-22 16:41 UTC, buildguy commented
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[![👍 Frogbot scanned this pull request and did not find any new security issues.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-12-22 16:41 UTC, buildguy commented
### :white_check_mark: Build finished in 29m 32s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
api,assemblies/pentaho-solutions,extensions
```
---
:ok_hand: All tests passed!
 
Tests run: **1678**, Failures: **0**, Skipped: **5** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/platform/job/PR-5811/12/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-12-22 17:09 UTC, merged